server:
  port: 8080
  host: "0.0.0.0"

rpc:
  timeout: 30s
  max_retries: 3
  retry_backoff: 1s
  ws_port: 8800
  ws_timeout: 45s
  requests_per_second: 50

collector:
  interval: 15s
  timeout_per_module: 10s
  batch_size: 3
  batch_interval: 2s
  
  # Collection priorities (higher number = higher priority)
  rpc_priority: 100
  cache_priority: 80
  ws_priority: 60
