server:
  port: 8080
  host: "0.0.0.0"
  path: "/solana/"
  timeout: 30s

rpc:
  endpoint: "http://localhost:8799"  # Default endpoint, can be overridden by VMPodScrape
  timeout: 10s
  max_retries: 3
  retry_backoff: 1s

collector:
  interval: 15s
  timeout_per_module: 5s
  concurrent_modules: 4
  batch_size: 100

metrics:
  labels:
    environment: "production"
    service: "solana-rpc"
  excluded_metrics:
    - "process_"
    - "go_"
  histogram_buckets:
    solana_rpc_latency_seconds:
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1
      - 2.5
      - 5
      - 10
    solana_block_processing_time:
      - 0.001
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
  default_buckets:
    - 0.005
    - 0.01
    - 0.025
    - 0.05
    - 0.1
    - 0.25
    - 0.5
    - 1
    - 2.5
    - 5
    - 10

system:
  enable_cpu_metrics: true
  enable_memory_metrics: true
  enable_disk_metrics: true
  enable_network_metrics: true

logging:
  level: "info"
  format: "json"
  file: "/var/log/solana-exporter.log"
