apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: solana-rpc-exporter
  namespace: monitoring
spec:
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  selector:
    matchLabels:
      app: solana-rpc-exporter
